# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: "yarn"
      - run: yarn install
  Build:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - run: yarn build
  Lint:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_dir: ./frontend
          eslint_extensions: js,jsx,vue,ts,tsx
          prettier: true
          prettier_dir: ./frontend
          prettier_extensions: js,jsx,vue,ts,tsx
          auto_fix: true
  Test:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
      - run: yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
