name: "coverage"
on:
  pull_request:
    branches: [master]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
